// <auto-generated />
namespace ICBA.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Addtablesandconnections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtablesandconnections));
        
        string IMigrationMetadata.Id
        {
            get { return "201711091358250_Add tables and connections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
