// <auto-generated />
namespace ICBA.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ChangeSensorIdtypefrominttoGuidinSensorHistoriestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeSensorIdtypefrominttoGuidinSensorHistoriestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711121207480_Change SensorId type from int to Guid in SensorHistories table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
